name: Spring Boot CI/CD

on:
  push:
    branches: [ "main" ]  # main 브랜치에 push될 때 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: JDK 17 설정
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle 권한 설정
        run: chmod +x ./gradlew

      - name: 빌드 & 테스트
        run: ./gradlew build

      - name: 서버에 배포
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "build/libs/andyou-0.0.1-SNAPSHOT.jar"
          target: "/home/ubuntu/app"

      - name: 서버에서 실행
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            pkill -f 'java -jar' || true
            nohup java -jar /home/ubuntu/app/andyou-0.0.1-SNAPSHOT.jar > app.log 2>&1 &